# Practical 1: Marginal Models for Continuous Data
We start by loading the packages we will need for this practical and the data from 
[GitHub](https://github.com/drizopoulos/Repeated_Measurements). This is achieved with the
following commands:
```{r}
# packages
library("lattice")
library("nlme")
library("splines")

# data
con <- url("https://raw.github.com/drizopoulos/Repeated_Measurements/master/Data.RData")
load(con)
close(con)
```

## Question 1
We 

```{r}
xyplot(prothrombin ~ year | drug, group = id, data = pbc2, 
       panel = function (x, y, ...) {
           panel.xyplot(x, y, type = "l", col = 1, ...)
           panel.loess(x, y, col = 2, lwd = 2)
       }, xlab = "Time (years)", ylab = "Prothrombin Time (sec)")
```

```{r}
xyplot(prothrombin ~ year | sex, group = id, data = pbc2, 
       panel = function (x, y, ...) {
           panel.xyplot(x, y, type = "l", col = 1, ...)
           panel.loess(x, y, col = 2, lwd = 2)
       }, xlab = "Time (years)", ylab = "Prothrombin Time (sec)")
```

```{r}
# 16 sample patients
ids <- c(133, 36, 180, 11, 168, 116, 70, 58, 82, 104, 
         43, 21, 101, 210, 176, 157)

xyplot(prothrombin ~ year | id,
       panel = function (x, y, ...) {
           panel.xyplot(x, y, type = "l", col = 1, ...)
           if (length(unique(x)) > 5)
               panel.loess(x, y, col = 2, lwd = 2)
       }, data = pbc2, subset = id %in% ids, layout = c(4, 4), as.table = TRUE, 
       xlab = "Time (years)", ylab = "Prothrombin Time (sec)")
```

## Question 2
```{r}
fm_1 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2)

summary(fm_1)
```

## Question 3
The following call to `gls()` fit the
```{r}
fm_2 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corCompSymm(form = ~ year | id))

fm_3 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corCAR1(form = ~ year | id))

fm_4 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corExp(form = ~ year | id))

fm_5 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corGaus(form = ~ year | id))
```

```{r}
fm_6 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corCompSymm(form = ~ year | id),
            weights = varExp(form = ~ year))

fm_7 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corCAR1(form = ~ year | id),
            weights = varExp(form = ~ year))

fm_8 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corExp(form = ~ year | id),
            weights = varExp(form = ~ year))

fm_9 <- gls(prothrombin ~ ns(year, 3) * (sex + drug) + age, data = pbc2, 
            correlation = corGaus(form = ~ year | id),
            weights = varExp(form = ~ year))
```

## Question 4

```{r}
anova(fm_1, fm_2)
anova(fm_1, fm_3)
anova(fm_1, fm_4)
anova(fm_1, fm_5)
```

```{r}
anova(fm_2, fm_3, fm_4, fm_5)
```

```{r}
anova(fm_6, fm_7, fm_8, fm_9)
```

```{r}
anova(fm_2, fm_6)
```